import 'package:flutter/foundation.dart';
import 'package:lakshya_mvp/core/repositories/enrollment_repository.dart';
import 'package:lakshya_mvp/models/enrollment.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Enrollment provider for managing enrollment state
/// 
/// Follows Provider pattern and SOLID principles
class EnrollmentProvider with ChangeNotifier {
  final EnrollmentRepository _repository;
  final SupabaseClient _client;

  List<Enrollment> _enrollments = [];
  Enrollment? _selectedEnrollment;
  bool _isLoading = false;
  String? _error;

  EnrollmentProvider(this._repository, this._client) {
    _loadEnrollments();
    _setupRealtimeSubscription();
  }

  List<Enrollment> get enrollments => _enrollments;
  Enrollment? get selectedEnrollment => _selectedEnrollment;
  bool get isLoading => _isLoading;
  String? get error => _error;

  /// Get enrollments for current user
  Future<void> _loadEnrollments() async {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) {
      _enrollments = [];
      notifyListeners();
      return;
    }

    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      _enrollments = await _repository.getByStudentId(userId);
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      _error = e.toString();
      _isLoading = false;
      debugPrint('Error loading enrollments: $e');
      notifyListeners();
    }
  }

  /// Check if current user is enrolled in a course
  Future<bool> isEnrolledInCourse(String courseId) async {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) return false;

    try {
      return await _repository.isEnrolled(
        studentId: userId,
        courseId: courseId,
      );
    } catch (e) {
      debugPrint('Error checking enrollment: $e');
      return false;
    }
  }

  /// Get enrollment for a specific course
  Future<Enrollment?> getEnrollmentForCourse(String courseId) async {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) return null;

    try {
      return await _repository.getByStudentAndCourse(
        studentId: userId,
        courseId: courseId,
      );
    } catch (e) {
      debugPrint('Error fetching enrollment: $e');
      return null;
    }
  }

  /// Create a new enrollment or update existing one
  Future<Enrollment?> enrollInCourse({
    required String courseId,
    bool paymentRequired = true,
  }) async {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) {
      _error = 'User not authenticated';
      notifyListeners();
      return null;
    }

    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      // Check if enrollment already exists
      final existingEnrollment = await _repository.getByStudentAndCourse(
        studentId: userId,
        courseId: courseId,
      );

      // If payment is not required, activate enrollment immediately
      // Otherwise, keep it pending until payment is confirmed
      final enrollmentStatus = paymentRequired 
          ? EnrollmentStatus.pending 
          : EnrollmentStatus.active;

      Enrollment result;
      
      if (existingEnrollment != null) {
        // Update existing enrollment
        final updatedEnrollment = existingEnrollment.copyWith(
          status: enrollmentStatus,
          paymentStatus: paymentRequired ? PaymentStatus.pending : PaymentStatus.notRequired,
          paymentRequired: paymentRequired,
        );
        result = await _repository.update(updatedEnrollment);
        debugPrint('Updated existing enrollment: ${result.id}');
      } else {
        // Create new enrollment
        final enrollment = Enrollment(
          id: '', // Will be generated by database
          studentId: userId,
          courseId: courseId,
          status: enrollmentStatus,
          paymentStatus: paymentRequired ? PaymentStatus.pending : PaymentStatus.notRequired,
          paymentRequired: paymentRequired,
          enrolledAt: DateTime.now(),
        );
        result = await _repository.create(enrollment);
        debugPrint('Created new enrollment: ${result.id}');
      }

      await _loadEnrollments(); // Refresh list
      return result;
    } catch (e) {
      _error = e.toString();
      _isLoading = false;
      debugPrint('Error enrolling in course: $e');
      notifyListeners();
      return null;
    }
  }

  /// Select an enrollment
  void selectEnrollment(Enrollment enrollment) {
    _selectedEnrollment = enrollment;
    notifyListeners();
  }

  /// Clear selection
  void clearSelection() {
    _selectedEnrollment = null;
    notifyListeners();
  }

  /// Refresh enrollments
  Future<void> refresh() async {
    await _loadEnrollments();
  }

  /// Start a free trial for a course
  Future<bool> startFreeTrial({
    required String courseId,
    required int trialDays,
  }) async {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) {
      _error = 'User not authenticated';
      notifyListeners();
      return false;
    }

    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      // Check if enrollment exists
      var enrollment = await _repository.getByStudentAndCourse(
        studentId: userId,
        courseId: courseId,
      );

      if (enrollment == null) {
        // Create enrollment with trial
        enrollment = Enrollment(
          id: '',
          studentId: userId,
          courseId: courseId,
          status: EnrollmentStatus.active,
          paymentStatus: PaymentStatus.pending,
          paymentRequired: true,
          enrolledAt: DateTime.now(),
          trialStartedAt: DateTime.now(),
          trialEndsAt: DateTime.now().add(Duration(days: trialDays)),
        );
        await _repository.create(enrollment);
      } else {
        // Update existing enrollment with trial
        final updatedEnrollment = enrollment.copyWith(
          status: EnrollmentStatus.active,
          trialStartedAt: DateTime.now(),
          trialEndsAt: DateTime.now().add(Duration(days: trialDays)),
        );
        await _repository.update(updatedEnrollment);
      }

      await _loadEnrollments();
      return true;
    } catch (e) {
      _error = e.toString();
      _isLoading = false;
      debugPrint('Error starting free trial: $e');
      notifyListeners();
      return false;
    }
  }

  /// Mark payment as complete for a course
  Future<bool> markPaymentComplete(String courseId) async {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) {
      _error = 'User not authenticated';
      notifyListeners();
      return false;
    }

    try {
      final enrollment = await _repository.getByStudentAndCourse(
        studentId: userId,
        courseId: courseId,
      );

      if (enrollment == null) {
        _error = 'Enrollment not found';
        notifyListeners();
        return false;
      }

      final updatedEnrollment = enrollment.copyWith(
        status: EnrollmentStatus.active,
        paymentStatus: PaymentStatus.paid,
      );
      await _repository.update(updatedEnrollment);
      await _loadEnrollments();
      return true;
    } catch (e) {
      _error = e.toString();
      debugPrint('Error marking payment complete: $e');
      notifyListeners();
      return false;
    }
  }

  /// Setup realtime subscription for enrollment updates
  void _setupRealtimeSubscription() {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) return;

    _client
        .from('enrollments')
        .stream(primaryKey: ['id'])
        .eq('student_id', userId)
        .listen((data) {
      // Reload enrollments when changes occur
      _loadEnrollments();
    });
  }

  @override
  void dispose() {
    // Cleanup handled by Supabase client
    super.dispose();
  }
}

