// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwwbHtlFbYovtAqVdIbVb-wI1we6kZPZw',
    appId: '1:925933038816:web:f458c5e181927571ba7485',
    messagingSenderId: '925933038816',
    projectId: 'paperlms-001',
    authDomain: 'paperlms-001.firebaseapp.com',
    storageBucket: 'paperlms-001.firebasestorage.app',
    measurementId: 'G-MLD3YMYKV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJq1xNgcUN6qmOzMj16EZPO_tCH8ZXsyw',
    appId: '1:925933038816:android:fed25a7df0473df9ba7485',
    messagingSenderId: '925933038816',
    projectId: 'paperlms-001',
    storageBucket: 'paperlms-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgzMKtnWfUiX7Rzo_b_Lq6l_BmjAP7Rhg',
    appId: '1:925933038816:ios:c52536d9a309d340ba7485',
    messagingSenderId: '925933038816',
    projectId: 'paperlms-001',
    storageBucket: 'paperlms-001.firebasestorage.app',
    iosBundleId: 'com.lakshya.lakshyaMvp',
  );
}
